version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Pacific/Auckland
  open-pull-requests-limit: 99
  reviewers:
  - kylorhall
  labels:
  - bot-pr
  - dependencies
  - javascript

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Pacific/Auckland
  open-pull-requests-limit: 99
  reviewers:
  - irwalker
  labels:
  - bot-pr
  - dependencies
  - ruby
  versioning-strategy: lockfile-only

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "Pacific/Auckland"
  labels:
  - dependencies
  - bot-pr
  - gh-actions
  reviewers:
  - "sharesight/dev-ops"
